kokkos/pykokkos

.gitignore

* pretty minor; add [standard `vim` tags](https://github.com/github/gitignore/blob/main/Global/Vim.gitignore) to `.gitignore` so
I don't see swap files in my checkout

MAINT: gitignore vim

---

.github/workflows/main_ci.yml
pykokkos/core/cpp_setup.py
pykokkos/interface/views.py
runtests.py
tests/test_AST_translator.py
tests/test_views.py

* run the actual tests in the CI--I developed this
locally using the [`act`](https://github.com/nektos/act) tool--the current blocker
seems to be that we have unguarded `import cupy`
in the both the codebase and the testsuite, so I'm
not sure how we do a pure `OpenMP` toolchain/testing
for vanilla GitHub Actions virtual machines that lack
GPUs/CUDA?

WIP, CI: run tests in CI

---

pykokkos/core/visitors/workunit_visitor.py
pykokkos/interface/__init__.py
pykokkos/interface/atomic/atomic_op.py

Add support for `pk.atomic_increment()`

Interface: add support for atomic_increment

---

pykokkos/core/compiler.py
pykokkos/core/module_setup.py

Compiler: call ModuleSetup.get_main_dir() instead of method

---

pykokkos/__init__.py
pykokkos/lib/ufuncs.py
tests/test_ufuncs.py

The ufuncs this PR covers include:
- add
- subtract
- multiply
- matmul
- divide
- negative
- positive
- power
- fmod
- square
- greater
- logaddexp
As of now these ufuncs only supports 1D (float and double) Views as input .

Added Multiple basic ufuncs

---

pykokkos/interface/views.py

Also includes a fix to an `np.array` call in the subview constructor

Change shape member variable to be a tuple instead of list

---

.github/workflows/array_api.yml
pykokkos/__init__.py
pykokkos/lib/create.py
pykokkos/lib/info.py
pykokkos/lib/manipulate.py
pykokkos/lib/ufuncs.py

* changes needed to pass `array_api_tests/test_creation_functions.py::test_ones_like`
* this builds on gh-73, and is meant to be reviewed after that one
* merge conflicts are likely...

ENH: changes needed to pass `array_api_tests/test_creation_functions.py::test_ones_like`

---

.github/workflows/array_api.yml

* pin `hypothesis` to temporarily avoid https://github.com/kokkos/pykokkos/issues/65#issuecomment-1262840467
until we have a proper implementation of that

CI: pin hypothesis

---

pykokkos/core/compile.sh
pykokkos/core/compiler.py
pykokkos/core/cpp_setup.py
pykokkos/interface/execution_space.py
pykokkos/interface/memory_space.py
pykokkos/interface/views.py

This PR adds support for HIP, enabling us to run PyKokkos on AMD GPUs. Credit to Neil Mehta for the original prototype.

PyKokkos: add support for HIP

---

pykokkos/core/translators/bindings.py
pykokkos/core/translators/functor.py

Revert "Make pykokkos export bindings for the generated functor"

---

examples/ExaMiniMD/src/examinimd.py
pykokkos/core/cpp_setup.py
pykokkos/interface/memory_space.py
pykokkos/interface/views.py

This adds HIPHostPinnedSpace support to pykokkos

PyKokkos: add support for HIPManagedSpace memory space

---

.github/workflows/array_api.yml
.github/workflows/main_ci.yml
.github/workflows/nightly.yml
examples/LogisticRegression/LR.py
mypy.ini
pykokkos/__init__.py
pykokkos/interface/views.py
pykokkos/lib/manipulate.py
pykokkos/lib/ufuncs.py
pykokkos/lib/util.py

This PR contains the basic working scikit learn's version of logistic regression.
We havent worked on the nested functions in this PR e.g. `sklearn.utils.validation.check_is_fitted` and a few others. As of now we just convert the output of these functions from numpy to pykokkos using `asarray`.
I am working on figuring out if we can get any significant gains from copying scikit learns internal functions and making them compatible with pykokkos.
This PR also fixes the mypy version to `0.981` because in the latest version mypy is testing some files which are in the ignore list (also pointed out [here](https://github.com/kokkos/pykokkos/pull/128#issuecomment-1326718976)).

Logistic Regression - Pykokkos example

---

benchmarks/dgemm_compare.py
pykokkos/interface/views.py
pykokkos/linalg/l3_blas.py
tests/test_linalg.py

* get some initial regression tests in place by adding a non-optimized DGEMM algorithm--specifically `Algorithm 1` from Kurzak et al. (2012)
* my main objective here is just to have some tests in place before we try to move on to more advanced algorithms or perhaps even autotuning? Not sure how far down that rabbit hole we plan to go just yet, and which knobs we can reasonably expect to turn from PyKokkos alone
@gliga @NaderAlAwar this starts what was briefly discussed in our email chain I think..

ENH: DGEMM non-optimized

---

benchmarks/dgemm_compare.py
examples/pykokkos/from_array.py
examples/pykokkos/multi_gpu.py
pykokkos/interface/__init__.py
pykokkos/interface/views.py
pykokkos/lib/util.py
tests/test_linalg.py
tests/test_views.py

Automatically convert cupy and numpy arrays (and other array like or convertabe objects) to a View without user input

Abstract the from_cupy and from_numpy functions with a wrapper

---

examples/GPU-Puzzles/README.md
examples/GPU-Puzzles/puzzle1.py
examples/GPU-Puzzles/puzzle2.py
examples/GPU-Puzzles/puzzle3.py
examples/GPU-Puzzles/puzzle4.py
examples/GPU-Puzzles/puzzle5.py

This PR provides solution for the first 5 puzzles.
I was initially hoping they would be more interesting to be done in PyKokkos, but our model is simpler than CUDA, so things either do not directly apply or they are simple.
Puzzles 6 and 7 no need to solve with PyKokkos. Worth taking a look at 8+.

 examples: Add solution to first 5 puzzles

---

pykokkos/interface/views.py

Previously we were storing a numpy array with a device memory pointer

Views: store cupy array in View object when creating View from cp.ndarray

---

examples/ExaMiniMD/workload/src/property_kine.py
pykokkos/core/visitors/kokkosmain_visitor.py
pykokkos/core/visitors/visitors_util.py
pykokkos/interface/views.py

This PR adds more support for using cupy/numpy arrays wrapped with Views. Also includes a fix to ExaMiniMD KinE workunit not compiling properly.

Further fixes to using ndarrays with Views

---

pykokkos/lib/ufuncs.py

`np,matmul` supports the case where two empty arrays e.g `[] @ []` return 0.0. 
This PR Adds the noted corner case to `pykokkos.np_matmul` ufunc

ufuncs.py: npmatmul now supports empty views

---

pykokkos/core/fusion/trace.py

Delayed workunits that write to subviews are not being executed even if later workunits depend on them. This PR checks if a workunit's input views are subviews and gets the parent view if that is the case.

Tracer: account for subviews when getting dependencies

---

pykokkos/interface/parallel_dispatch.py
pykokkos/lib/ufuncs.py
pykokkos/lib/util.py

This makes it easier to time some of these ufuncs through the kokkos profiler

Ufuncs: allow passing string for kokkos profiler kernel name for some ufuncs from npbench
