kokkos/pykokkos

- examples/kokkos/02_simple_reduce.py
Fixes #6 (well up to a smaller value at least..)
* use a larger type for the total variable
in `02_simple_reduce.py` to prevent overflow
at larger square sum values, and to match
the type of the accumulator that is used
* this seems to allow `9000` to be handled,
though not `90000`, based on comparison
with i.e., `np.sum(np.arange(9000) ** 2)`
* I also noticed that this adjustment
only helps if I manually purge the `pk_cpp`
folder (no recompile on the variable
type change?)
> MAINT: use a larger type for simple_reduce

- tests/test_kokkosfunctions_translator.py
Fixes #9
* use the NumPy testing function `assert_allclose()`
for the floating-point assertion in `test_float_sum()`
because requiring exact floating point equality was
causing falures for me on one of our `clx-volta` nodes
* I'm assuming that a dependency on NumPy for the
testsuite should be "ok" (test-time deps are usually
less serious than runtime deps, etc.)
> TST: assert_allclose for test_float_sum

- pykokkos/core/translators/bindings.py
* the tests seem to pass without this duplication
detected by `mypy`; I haven't yet checked if the
current tests flush this code path though
* the original `mypy` complaint was:
- `pykokkos/core/translators/bindings.py:179: error: Name "view_type" already defined on line 173`
Incidentally, I was kind of thinking a scoped `mypy` check might be an easy way to get CI rolling (i.e., start with a tiny bit of static type analysis, then ramp up to `runtests.py` and all the compiled dependencies).
> MAINT: rm duplication in bindings module

- runtests.py
* adjust `runtests.py` to purge the compiled
"cache" between tests, otherwise we might miss
compilation issues while iterating on the code
* on one of our `clx-volta` nodes this changes the
repeated test suite time on a single core from around
25 seconds to 185 seconds, which is consistent with
the translation/compilation happening on each repeat
incantation of the test suite
> TST: purge cache when testing

- runtests.py
* add the ability to run specific test modules/classes/files
with `runtests.py`, largely copying the design from SciPy/NumPy
* note that they are considering a complete overhaul of their
CLI tools (https://github.com/scipy/scipy/issues/15489) but for
now I'm just trying to mimic the crucial things we need for `pytest`
* some example incantations on this branch:
- run a single test module: `python runtests.py -t tests/test_views.py`
- `9 passed, 3 warnings in 77.47s (0:01:17)`
- run an individual test: `python runtests.py -t tests/test_atomics.py::TestAtomic::test_atomic_xor`
- `1 passed, 3 warnings in 12.55s`
- run a single test class: `python runtests.py -t tests/test_atomics.py::TestAtomic`
- `12 passed, 3 warnings in 12.81s`
- run the entire suite again: `python runtests.py`
- `89 …
> TST: runtests specific tests

- .github/workflows/main_ci.yml
- mypy.ini
* Add config file for `mypy` such that no errors are raised
* Add GitHub actions CI testing
This is an initial trial that I tested on my [fork](https://github.com/nawtrey/pykokkos/pull/1) with Python 3.8-3.10, which passed for all 3 Python versions. The CI is currently pinned to the `develop` branch, and I have the `mypy.ini` set to ignore basically every module. There are simpler ways of accomplishing this, but I went with a per-module approach so they can easily be removed one at a time, and corrected in subsequent PR's. Eventually it would be nice to have all of the modules passing, of course. 
Commenting out any module will result in some number of errors (as many as 50+ for some), with the exception of the `mypy-pykokkos.bindings.bindings.libpykokkos`, which only raised an error in …
> WIP, CI: Add initial CI with mypy

- .github/workflows/main_ci.yml
* [follow NumPy](https://github.com/numpy/numpy/pull/21307) in bumping the GitHub `actions` to
their latest versions
> CI: bump GHA versions

- pykokkos/__init__.py
- pykokkos/core/runtime.py
- pykokkos/core/translators/bindings.py
- pykokkos/interface/parallel_dispatch.py
This PR caches the wrapper function handles for workunits to avoid the run-time performance overhead of importing the compiled module and retrieving the function handle, as well as processing the arguments passed to the workunit.
Another commit also replaces the Kokkos::fence() call with an execution space specific fence() to reduce overhead.
> Reduce run-time performance overhead

- pykokkos/core/parsers/parser.py
Fix parser crashing issue reported in kokkos/pykokkos#22.
> Parser: fix crash caused by functions decorated with chained names 

- pykokkos/core/visitors/workunit_visitor.py
- tests/test_parallelreduce.py
Fixes #24
* we can now use `pk.int64` for variables (beyond
the accumulator) in parallel reductions, which
improves our range of integer reduction sizes
* remove the known failure from `test_squaresum_types()`
since we now match NumPy for `np.int64` at larger
values there
> ENH: reduction type expand

- pykokkos/__init__.py
- pykokkos/lib/ufuncs.py
- tests/test_ufuncs.py
* draft of new `pk.reciprocal()` "ufunc" exposed
for initial usage with 1D arrays of type `double`
* the diff contains various comments/design questions,
which is why I've only drafted 1 ufunc here so far; another
thing to keep in mind is how closely we'd like to match
the arguments from the original ufunc:
https://numpy.org/doc/stable/reference/generated/numpy.reciprocal.html
It is a bit tricky to compare timings, but with 4 OpenMP threads set
in my environment, `pykokkos` can perform quite a bit faster after
paying the cost of the initial compilation (which NumPy paid
previously when it was built ahead of time):
<details>
<summary> Small Python timing script details are below the fold </summary>
```python
import time
import numpy as np
from numpy.testing import assert_allclose
import …
```
> ENH: expose pk.reciprocal

- .github/workflows/nightly.yml
Fixes #30
* add a nightly cron test of our `develop` vs. Kokkos `develop`
branch
* you can run/test it locally using the [`act`](https://github.com/nektos/act) tool
with i.e., `act -j test_vs_kokkos_develop`
* at the moment, it correctly detects the test failures
described in gh-32
> CI: nightly vs. Kokkos develop

- pykokkos/interface/views.py
- tests/test_views.py
Fixes #31
* include a regression test for 1D through 3D
views vs. NumPy `size` attributes
> ENH: support size attribute for views

- pykokkos/__init__.py
- pykokkos/interface/parallel_dispatch.py
- pykokkos/lib/ufuncs.py
- tests/test_ufuncs.py
* add `double` and `float` versions of `pk.sqrt()`, and some tests to enforce behavioral similarity with `np.sqrt()` in 1D
* this PR temporarily cherry-picks the commit from gh-35, so that we can avoid caching/reference management issues that would otherwise prevent the expanded ufunc tests from passing
> ENH: add pk.sqrt ufunc in 1D

- pykokkos/lib/ufuncs.py
- tests/test_ufuncs.py
* `pk.reciprocal` ufunc now handles
2D views and a test against NumPy 2D
behavior has been added
> ENH: 2D reciprocal ufunc

- mypy.ini
- pykokkos/__init__.py
- pykokkos/core/visitors/visitors_util.py
- pykokkos/lib/ufuncs.py
- tests/test_ufuncs.py
* add support for `pk.sign` ufunc on 1D views of type
`double` and `float`, and add regression tests against
the NumPy implementation
* this includes adding support for the C++ `nan()` `cmath`
function in workunits
* for now, we ignore type hints in the ufuncs module; can't
get that to behave properly with `mypy` yet
* I also tested the `pk.sign` implementation in SciPy itself,
with the motivation of eventually replacing larger chunks of
SciPy code with pykokkos ufuncs; see diff below or my feature
branch `treddy_voronoi_pykokkos_testing`, which appears to
pass the SciPy suite for this part of the code with
`time python dev.py test -j 1 -t scipy/spatial/tests/test_spherical_voronoi.py`
(as long as `pytest-xdist` is not used because of gh-14)
```diff
diff --git …
```
> ENH: support for 1D pk.sign

- .github/workflows/array_api.yml
- mypy.ini
- pykokkos/__init__.py
- pykokkos/interface/__init__.py
- pykokkos/interface/data_types.py
- pykokkos/interface/views.py
- pykokkos/lib/create.py
- pykokkos/lib/info.py
- pykokkos/lib/util.py
Related to #56. This at least allows us to run the array API conformance test suite, rather than erroring out at import time. I suspect some of the changes here we won't really want to make, but on the flip side this gives folks an idea of some of the changes I needed to get us even remotely close to being able to run the suite.
* support the bare minimum required types per:
https://data-apis.org/array-api/2021.12/API_specification/data_types.html
(otherwise, we can't even import the array API tests, let
alone run them--for now, some types are basically just "stubs"
and/or aliases so we can get things rolling)
* support `iinfo` and `finfo` functions required by the standard:
https://data-apis.org/array-api/2021.12/API_specification/data_type_functions.html#objects-in-api
* needed to add a …
> ENH: array API start

- .github/workflows/array_api.yml
* temporarily pin the array API testsuite version used
in CI to avoid gh-63; I tested with the
[`act`](https://github.com/nektos/act) tool locally and it seems to pass
* we can unpin when there's an upstream fix, though we may
want to stay pinned for some time and only occasionally
bump to the latest version after testing it
> CI: pin array API suite

- .github/workflows/main_ci.yml
* Python `3.11` RC1 is ABI stable, so might
as well test against it
* we should be able to remove the custom `pybind11`
submodule checkout once we update upstream per:
https://github.com/kokkos/pykokkos-base/issues/44
> CI: add Python 3.11 RC1 to CI

- pykokkos/core/cppast/decl.py
- pykokkos/core/visitors/visitors_util.py
- pykokkos/interface/__init__.py
- pykokkos/interface/data_types.py
- pykokkos/interface/views.py
* add the `int8` and `uint8` types following
the upstream PRs:
https://github.com/kokkos/pykokkos-base/pull/47
https://github.com/kokkos/pykokkos-base/pull/43
* these are required for array API conformance per:
https://data-apis.org/array-api/latest/API_specification/data_types.html
* I was also thinking `uint8` may be a suitable proxy
for `bool` one way or another, unless we can easily use
an even smaller custom type for that
> ENH: add int8/uint8

- .github/workflows/main_ci.yml
* following the upstream merge of https://github.com/kokkos/pykokkos-base/pull/46
we should no longer need to manually update the `pybind11` submodule
within `pykokkos-base`
> CI: simplify pybind11

- pykokkos/__init__.py
- pykokkos/core/visitors/visitors_util.py
- pykokkos/lib/ufuncs.py
- tests/test_ufuncs.py
The ufuncs this PR covers include:
- true_divide
- logaddexp2
- floor_divide
- sin
- cos
- tan
- logical_and
- logical_or
- logical_xor
- logical_not
- fmax
- fmin
- exp
- exp2
As of now these ufuncs only supports 1D (float and double) Views as input .
> Multiple arithmetic, logical, and trigonometric ufuncs

- .github/workflows/array_api.yml
- .github/workflows/main_ci.yml
- pykokkos/__init__.py
- pykokkos/interface/views.py
- pykokkos/lib/constants.py
- pykokkos/lib/ufuncs.py
- setup.py
- tests/test_views.py
* Fixes #68 by adding the `pk.e`, `pk.pi`, `pk.inf`, and `pk.nan` constants needed to pass `array_api_tests/test_constants.py` (we'll see if the CI agrees with me...)
* the implementations are a bit crude, but do seem to pass tests locally at least
* note that some of the infrastructure here is borrowed from other unmerged PRs
> ENH: add API constants

- pykokkos/interface/views.py
- tests/test_views.py
Fixes #86
* prohibit negative values in `pk.uint32`/`pk.uint64`-specified views, and match the "wrapping" behavior used by NumPy in these cases
> BUG: uint32/64 wrapping

- pykokkos/interface/data_types.py
- pykokkos/interface/views.py
* this splits off a few cleanups from gh-73
* there is some pointless type remapping code in the `View` class that has been removed
* removing the above code causes the test suite to fail because of incorrect `uint32`/`uint64`
`value` mappings in `data_types` module, so fix
those to allow tests to pass
> MAINT, BUG: typing cleanups

- .github/workflows/array_api.yml
- pykokkos/__init__.py
- pykokkos/interface/views.py
- pykokkos/lib/create.py
- pykokkos/lib/ufuncs.py
- pykokkos/lib/util.py
Fixes #70
* implement `pk.ones()` such that
`array_api_tests/test_creation_functions.py::test_ones` passes
* the Python array API standard `test_ones()` makes use
of `pk.equal()`, which wasn't implemented, so an early-stage
implementation is added here (which should help later on as well,
since the need to occasionally do `view1 == view2` should be
obvious)
* this is no doubt a bit of a "hack," especially in terms
of full-featured broadcasting for `pk.equal`, which is currently only
supported for "scalar" broadcasting in my work here
* I was a bit surprised that I only needed to add limited 1D
support for `pk.equal()`, but I imagine the code there will grow
substantially to support more scenarios/remove hacks in the future
* note that this branch also borrows some of the typing
changes …
> ENH: pk.ones() to API standard

- runtests.py
* add an option to report the top `N` slowest tests when running `runtests.py`, which basically
just passes through to the built-in pytest option: https://docs.pytest.org/en/7.1.x/how-to/usage.html#profiling-test-execution-duration
* I'm hoping not to build many more options in though, I just wanted this one because we'll want a convenient way to keep an eye on what tests are consuming time as our suite grows
* some sample incantations/results:
- `python runtests.py -d 10`
```
===================================================================================================================================================
slowest 10 durations
=================================================================================================================================================== …
```
> TST, MAINT: test durations

- examples/pykokkos/multi_gpu.py
- pykokkos/__init__.py
- pykokkos/core/compile.sh
- pykokkos/core/compiler.py
- pykokkos/core/cpp_setup.py
- pykokkos/core/module_setup.py
- pykokkos/core/runtime.py
- pykokkos/core/translators/bindings.py
- pykokkos/interface/__init__.py
- pykokkos/interface/execution_space.py
- pykokkos/interface/views.py
- pykokkos/kokkos_manager/__init__.py
This PR enables using multiple CUDA GPUs in PyKokkos in the same process. It depends on another pykokkos-base https://github.com/kokkos/pykokkos-base/pull/48 which makes multiple copies of libpykokkos, libkokkoscore, and libkokkoscontainers. PyKokkos will then link kernels compiled for CUDA to a different set of libraries depending on the GPU specified by the user.
The concept of Multi-GPU Kokkos is based on William Ruys's work [here](https://github.com/ut-parla/Parla.py/tree/main/examples/kokkos)
> Enable usage of multiple GPUs in PyKokkos

- .github/workflows/array_api.yml
- pykokkos/interface/__init__.py
- pykokkos/interface/views.py
- tests/test_views.py
* add changes needed to support the array API data type function `result_type()`, which is tested by
`array_api_tests/test_data_type_functions.py::test_result_type` and described in the standard at:
- https://data-apis.org/array-api/latest/API_specification/generated/signatures.data_type_functions.result_type.html?highlight=result_type
- https://data-apis.org/array-api/latest/API_specification/type_promotion.html#type-promotion
* surprisingly, this relatively simple draft logic already passes the array API test, but I'm certain this is far too simple to handle all cases for us beyond the simplest ones; still, it is a start on our type promotion rules
* I don't think this will work with views yet (or what we'll eventually call arrays), but it seems to pass the dtype tests used by the …
> ENH: support result_type

- .github/workflows/array_api.yml
- pykokkos/interface/views.py
- pykokkos/lib/ufuncs.py
* changes needed to pass `array_api_tests/test_operators_and_elementwise_functions.py::test_log10`, and start testing this in our CI
* this brings our `log10` ufunc closer to the array API standard based on the above test from their conformance suite; we handle 0-D and 2-D input for this ufunc now as well (as the test required)
* I'm not so sure we actually want to dispatch to any kind of parallel kernel for 0-D input to be honest, but I've done this for now...
* we no longer mutate input views for `log10` (more similar to NumPy..), instead allocating a new one to assign the result to
* `Subview`s were missing a few attributes required to pass the above test
* the test required that I start adding basic support for converting size-1 `View` objects like `[0]` to Python scalars via …
> ENH: log10 to API standard

- .github/workflows/array_api.yml
- pre_compile_tools/pre_compile_ufuncs.py
- pykokkos/lib/ufuncs.py
* as discussed briefly on Slack, this is a draft branch for precompiling a subset of the ufuncs
to avoid JIT slowdown errors like the one
described here for the `hypothesis`-driven array
API conformance test suite:
https://github.com/kokkos/pykokkos/pull/97#issuecomment-1261624809
* for now, this focuses on `pk.double` type in a single dimension, simply because all ufuncs should support that for pre-compilation at this time (we can broaden the dim/type pre-compile as ufuncs gain more flexibile type/dim support)
* one major issue I see here is that I don't think the pre-compilation will actually do anything useful yet because of how the `pk_cpp` directory structures work on a per-module non-shared hierarchy basis:
- pre-compilation module `pk_cpp` hierarchy:
- `pytest` `pk_cpp` hierarchy:
> WIP, MAINT: pre-compile ufuncs

- .github/workflows/main_ci.yml
* bump CI testing to Python `3.11rc2`--the final release is just a few weeks away now
* as reminder, the Python release candidates are considered both API and ABI stable vs. final release:
https://www.python.org/downloads/release/python-3110rc2/
* I doubt we'll see anything change from rc1->rc2 on our end, by why not check I guess
> MAINT, CI: Python 3.11 rc2

- pykokkos/core/cpp_setup.py
The tuple the function should return should contain 3 paths but never did when pykokkos is configured to use an external Kokkos lib via `PK_KOKKOS_LIB_PATH`. Came up because ArborX uses Kokkos 3.6.01
> added compiler_path when using env variable to point to kokkos install

- pykokkos/core/translators/bindings.py
- pykokkos/core/translators/functor.py
From a discussion I had with @NaderAlAwar about extending the interoperability with C++. The main reasoning was the following:
If we let people write their functors in python and expose the generated C++ functors (incl. bindings) we enable people to use pybind for generating wrappers. Anyone who uses pykokkos for creating a binding to a C++ library that uses kokkos can use the functors as arguments to calls to his C++ library and then bind them. Basically we allow people to export functors (and thus algorithms/logic) into bindings of their own C++ libs.
Some considerations:
- Our functor requires every argument to be default constructible ... we should document that. We would not necessarily have to allow this but that is how it is at the moment.
- Thus it is no problem to also allow the …
> Make pykokkos export bindings for the generated functor

- .github/workflows/array_api.yml
- pykokkos/__init__.py
- pykokkos/lib/info.py
* this is in part a copy of the NumPy patch applied at: https://github.com/numpy/numpy/pull/22365
and is related to this failure we were seeing with `hypothesis`: https://github.com/kokkos/pykokkos/issues/65#issuecomment-1262840467
* the standard section related to this is: https://data-apis.org/array-api/latest/future_API_evolution.html#versioning
* unpin `hypothesis` in our CI as a result; to be fair, this is the solution @ShahzadUmair wanted from the start I think
* the updated testing behavior required me to cherry-pick some data type info improvements from gh-97
> ENH: add __array_api_version__

- .github/workflows/main_ci.yml
Fixes #83
* we should no longer need to pin to Python `3.10.6` in CI based on the
discussion I'm seeing upstream (see link in matching issue)
> CI: unpin Python 3.10

- pykokkos/core/visitors/visitors_util.py
- pykokkos/kokkos_manager/__init__.py
The `PK_NO_VIEW_HOOKS` environment variable can be set if an older Kokkos version is used
> Translator: add view hook template argument to view type for Kokkos 3.7

- pykokkos/core/runtime.py
This gives the runtime a function called `precompile_workunit` that triggers the translation, compilation, and binding of a single `workunit`. The execution space can be given, otherwise it defaults to the ... default.
The main intent here is that other libs using the functors generated by pykokkos should have an easy way to request the compilation from anywhere, thus the integration into the runtime which is a singleton.
> Allow runtime to precompile individual `workunit`

- mypy.ini
* a recent `mypy` update is causing some errors for `pykokkos` functions defined with return values but no function bodies, like this:
```python
def team_size(self) -> int:
pass
```
* it may be that the author intended to mark these as say "abstract methods" that are to be implemented by inheriting classes, but I'm not sure, so for now I'm just relaxing the `mypy` configuration stringency so that we pass the static analysis again
> MAINT: mypy empty body fix

- pykokkos/core/compiler.py
- runtests.py
- tests/_logging_probe.py
* Fixes #125
* to prevent changing the default logging level of other Python libraries globally when importing `pykokkos`, we set its default log level to the Python standard library default and use `PK_LOG_LEVEL` env variable if we really want to change it
* `pytest` intercepts log activity in a tricky way, so at least for now the regression test I've added is a bit more creative than I'd like, but it does fail before/pass after
> BUG: logging normal default

- pykokkos/kokkos_manager/__init__.py
- tests/test_views.py
Fixes #126
* the testsuite hasn't been passing on machines with GPU support enabled for quite some time (probably about a month, we don't have CI for this of course)
* this appears to have started with the attempt to add support for handling multiple GPUs, where
an assumption was made that we can safely assume
that there are Python modules called `gpu0`, `gpu1`, and so on (we can't)
* to make matters worse, the exception handling caught the generic `Exception` object, suppressing any exception from providing more helpful information, and preventing the `GPU_BACKEND` constant from being set, so that we can't use at least part of the GPU infrastructure, resulting in failures in `test_views`
* the patch here tries to uncouple setting the `GPU_BACKEND` from the ability to successfully setup …
> BUG: GPU support broken

- .github/workflows/array_api.yml
* use a tagged release of the array API conformance test suite to follow up on: https://github.com/kokkos/pykokkos/issues/63#issuecomment-1228726381
* this seems safe when I test locally at least--we'll see if the CI agrees
* this splits off the similar change from gh-124, to simplify that PR a little
> MAINT, CI: use API tests 2022.09.30

- mypy.ini
- pykokkos/core/compiler.py
- pykokkos/core/cpp_setup.py
- pykokkos/core/translators/bindings.py
- pykokkos/core/translators/functor.py
- pykokkos/core/translators/functor_cast.py
- pykokkos/core/translators/static.py
This pr proposes custom "cast" functions to convert from a python object of the functor into the corresponding c++ functor. This allows other bindings that bind c++ libs that use kokkos to use pykokkos-generated functors in their bindings.
Why is it not a conventional "cast" operator but a free function?
A pybind11 cast operator would need to know how to construct the python object the functor wants to cast into. This is a problem as we do not know where the user defines the functor object and I did not want to import the main script into the c++ binding code just to know how to construct the functor object in c++.
This is solved by passing in a python object when casting from the c++ object to the python object. This leaves it to the user that calls the cast that the python object …
> Functor cast operators for interoperability with c++

- mypy.ini
- pre_compile_tools/pre_compile_ufuncs.py
- pykokkos/lib/ufunc_workunits.py
- pykokkos/lib/ufuncs.py
Fixes #135
* use a ufunc workunit dispatcher to improve concision of the ufunc code for these ufuncs,
as an initial demonstration:
- `isfinite()` (`parallel_for`)
- `equal()` (`parallel_for`)
- `isinf()` (`parallel_for`)
- `matmul()` (`parallel_reduce`)
- `reciprocal()` (`parallel_for`)
* the reduction in LOC is around: 250
* the changes do not guarantee identical behavior beyond the testsuite passing, so for example
error handling behavior may not be fully preserved
* our type system still needs a cleanup to make things more consistent per gh-80
> ENH: ufunc dispatcher/concision

- pykokkos/interface/parallel_dispatch.py
- tests/test_regressions.py
* Fixes #173
* add a regression test for gh-173 and fix the issue by invalidating the workunit cache when user-defined variables are used in a kernel
* this just builds on my previous skepticism that our cache is actually "safe"/useful as you can see
from the previous comments in the code in this area
* this fix may be more aggressive than needed, but since this fixes a bug it seems justified to me even if there is a broader performance implication, since the tests clearly are not in place to handle these cases
> BUG: fix caching for user-defined functor vars

- .github/workflows/array_api.yml
- .github/workflows/main_ci.yml
* local testing suggests it should be safe to bump to the latest stable release of `mypy`, so let's see if CI agrees
* it can be ~40 % faster in the `1.0` series (https://mypy-lang.blogspot.com/2023/02/mypy-10-released.html), though I doubt this matters much for us
> MAINT, CI: mypy bump

- mypy.ini
- pykokkos/core/compiler.py
- pykokkos/core/cpp_setup.py
- pykokkos/core/runtime.py
- pykokkos/interface/__init__.py
- pykokkos/interface/ext_module.py
- tests/test_ext_module.py
based on #107. Adds interface to `runtime` class to let users compile an external module by providing the source code.
The external module is compiled with the same compilation script as the rest of the pykokkos stuff to ensure, that there is no configuration mismatch.
The test shows the basic usage for a very simple external module.
> Allow users to use pykokkos to compile their own modules from source

- pykokkos/core/visitors/visitors_util.py
- tests/test_AST_translator.py
Fixes #180
* allow for scratch memory to be viewed as type `double`, including a regression test
* this is needed for shared memory usage in the DGEMM tiling algorithm (D = `double`)
* it turns out that `float` was aliased to `double`, which is incredibly confusing--I've adjusted such that `float` means `float` and `double` means `double`, which seems like the only sane design
> ENH: allow type double scratch

- pykokkos/core/translators/bindings.py
Fixes #187 ... Looks like I forgot a `not` for a condition when changing the bindings for the generated functor. 
The mistake was introduced in #107
> Use right if-condition for view assignments in functor translation

- pykokkos/core/translators/bindings.py
- pykokkos/core/translators/functor.py
- pykokkos/core/visitors/kokkosmain_visitor.py
- pykokkos/core/visitors/workunit_visitor.py
- tests/test_regressions.py
Fixes #192.
So far we used empty structs with the workunit name as tagname in the generated cpp code. This results in ambiguity if the workunit has the same name as the function it is calling. A prominent example is the `sin` that @tylerjereddy discovered in #192.
This PR renames the tags by adding `_tag` to the definition. This naming was chosen to increase readability on the cpp side while resolving the ambiguity.
> Append '_tag' to tags in generated cpp code

- .github/workflows/array_api.yml
- .github/workflows/main_ci.yml
* adjust our GHA CI configs to run on PRs against `main` given switch to development on `main` noted at:
https://github.com/kokkos/pykokkos/pull/198#issue-1704592469
> CI: run on main

- pykokkos/core/visitors/visitors_util.py
- pykokkos/interface/args_type_inference.py
- tests/test_typeinference.py
Two fixes to the code base:
- TraitDefault specifier is now recognized in the decorator list
- Moved the logic to skip type inference (if the user already annotated everything) to the very beginning
> Fix: TraitDefault specifer & Type inferrence skipping

- Dockerfile
- pk
- requirements.txt
The goal of this PR is to enable us to run pykokkos in a docker container. The items included:
* Dockerfile to let us build the image (this is focusing on CPU runs at the moment)
* Script that can use pykkokos image to run tests and examples in a container
* requirements.txt to ensure more control over versioning
Some decision decisions:
* Use `pykokkos` as the name for the image (note that later we might add other images for `-cuda` or `-hip`). Maybe `-cpu` could be added, but I did not feel like it.
* Use `pk` as the username (because I felt there are many pykokkos things around already).
* Potentially went a bit too far with being strict on version numbers, but felt good about it (as we can relax things in the future)
One thing we will probably want to add into the `pk` script is to …
> docker: Set up for building our image and running tests/code

- pykokkos/core/compiler.py
- pykokkos/core/module_setup.py
- pykokkos/core/parsers/parser.py
- pykokkos/core/runtime.py
- pykokkos/interface/__init__.py
- pykokkos/interface/args_type_inference.py
- pykokkos/interface/parallel_dispatch.py
- tests/test_typeinference.py
In continuation to previous version of type inference, now introducing a series of improvements:
- Decorator specifiers logic has been made separate from type inference - and these decorators will always override user provided ones
- Refactored to simplify type inference
- Keyword arguments can now be passed in any order with respect to the signature for inference to work
- Separated AST injection/fix calls for type annotation insertion and decorator insertion
> Decorator generation + Polished type Inference

- pykokkos/core/compiler.py
- pykokkos/core/fusion/fuse.py
- pykokkos/core/parsers/parser.py
- pykokkos/core/runtime.py
- pykokkos/core/translators/members.py
- pykokkos/core/visitors/workunit_visitor.py
- pykokkos/interface/parallel_dispatch.py
Remove `deepcopy()` from the parser when retrieving workunits to avoid unnecessary overhead. Previously it was done for every workunit AST since fusion requires that we modify the ASTs. We still `deepcopy()` but only for fused workunits and only after we check whether the fused workunit has already been compiled, greatly reducing the overhead by PyKokkos.
> Improve performance of kernel fusion by eliminating unnecessary deep copy

- pykokkos/core/compile.sh
> Build python bindings with the same cxx standard as kokkos.

- examples/BabelStream/functor/babel_stream.py
- examples/BabelStream/standalone/babel_stream.py
- examples/BabelStream/workload/babel_stream.py
- examples/ParRes/workload/nstream.py
- examples/ParRes/workload/stencil.py
- examples/ParRes/workload/transpose.py
- examples/kokkos-benchmarks/functor/bytes_and_flops.py
- examples/kokkos-benchmarks/functor/gather.py
- examples/kokkos-tutorials/functor/subview.py
- examples/kokkos-tutorials/standalone/subview.py
- examples/kokkos-tutorials/workload/subview.py
- examples/kokkos/scan_functor.py
- examples/kokkos/scan_standalone.py
- examples/kokkos/scan_workload.py
- examples/pykokkos/binsort.py
- examples/pykokkos/streams.py
- examples/pykokkos/subviews.py
- pykokkos/core/compile.sh
> Fix examples that fail because Kokkos::finalize called too early

- pykokkos/interface/views.py
- pykokkos/lib/manipulate.py
- pykokkos/lib/ufunc_workunits.py
- pykokkos/lib/ufuncs.py
- pykokkos/lib/util.py
This PR introduces a number of changes to views.py to address the Array API CI failures:
1. Avoid hashing list in asarray by checking the input type
2. Store temporary array introduced in asarray to avoid it being garbage collected
3. Use the data_types.py classes instead of enums
4. Handle boolean arrays better by explicitly using uint8
fixes #201
> Fix Array API CI failures

- pykokkos/core/compiler.py
- pykokkos/core/fusion/fuse.py
- pykokkos/core/runtime.py
Use `id()` to identify arguments passed to fused workunits that are the same and combine them into a single argument. Currently guarded with an environment variable.
> Add option to fuse kernel arguments

- mypy.ini
- pykokkos/core/compiler.py
- pykokkos/core/parsers/parser.py
- pykokkos/core/runtime.py
- pykokkos/core/type_inference/__init__.py
- pykokkos/core/type_inference/args_type_inference.py
- pykokkos/interface/__init__.py
- pykokkos/interface/parallel_dispatch.py
This PR intends to give type inference source code its proper place in the core sub-directory. 
- Moved the existing args_type_inference into its own package in core/type_inference (we can expand here)
- Redid all imports/references
> Refactor: Moving type inference to core

- pk
This PR changes our script for working with docker to use the actual image uploaded to the hub.
Additionally it makes the naming of functions more uniform.
Once this is merged, an example with a docker can be run like this
```
./pk pk_example examples/kokkos-tutorials/workload/01.py
```
This will pull the latest image and then run the example in a container. Running another example simply requires changing the path at the end.
> docker: Pull the image and uniform naming

- README.md
This PR describe the way our Docker image should be used for running and developing.
We should decide (separate from this PR) if we want to have `-dev` image independent from a default one that would be used for running examples.
(Once we have an image for CUDA as well, we should remove Installation instructions from the README file.)
> doc: Include Docker image usage

- pykokkos/core/compiler.py
- pykokkos/core/fusion/fuse.py
- pykokkos/core/parsers/parser.py
- pykokkos/core/runtime.py
- pykokkos/core/type_inference/__init__.py
- pykokkos/core/type_inference/args_type_inference.py
- pykokkos/interface/parallel_dispatch.py
This PR removes dependence on inspect library for type inference pipeline. This restructure includes:
- Reading of types now happens in the runtime object in `runtime.py` using the parser.
- This means that the parser is now initialized first in `runtime.py` using the compiler object already available
- Original parameters and their annotation are now read from the workunit AST itself.
- Runtime object now has a cache for the original state of the arguments node in the AST (to reset the arguments for the next call to the workunit)
> Removing dependence on inspect

- mypy.ini
- pykokkos/__init__.py
- pykokkos/core/__init__.py
- pykokkos/core/compiler.py
- pykokkos/core/fusion/__init__.py
- pykokkos/core/fusion/access_modes.py
- pykokkos/core/fusion/future.py
- pykokkos/core/fusion/trace.py
- pykokkos/core/runtime.py
- pykokkos/core/type_inference/__init__.py
- pykokkos/core/type_inference/args_type_inference.py
- pykokkos/core/visitors/kokkosmain_visitor.py
- pykokkos/interface/__init__.py
- pykokkos/interface/bin_sort.py
- pykokkos/interface/parallel_dispatch.py
- pykokkos/interface/views.py
Implement delayed execution in PyKokkos. This is enabled when the environment variable `PK_TRACE` is set. Delayed operations are executed either through `pk.flush()` or when the data that depends on those operations is accessed. This data can be either a Future returned from a reduction or scan or a View.
> Add feature for delayed execution of kernels

- pk
- pykokkos/core/cppast/serializer.py
- tests/test_AST_translator.py
This PR replaces the `pass` statement with `{}` rather than "". As a result, we do not observe errors when we have a surrounding block that is empty, e.g., an empty workunit with only `pass` in the body.
Also, a simple test for the pass statement is added.
Finally, the `pk` script is slightly extended to enable passing command line arguments to the script being executed, e.g., runtests.py (which enables selecting tests).
This PR addressing the issue: https://github.com/kokkos/pykokkos/issues/232
> Add support for the pass statement in trivial cases (empty body)

- README.md
- pk
This PR makes only minor changes to the documentation to emphasize the use of Docker and modifies the opening paragraph to detach from implementation details.
> doc: Revising README to focus on Docker

- pykokkos/kokkos_manager/__init__.py
This will resolve the issue of `pk.set_device_id(0)` incorrectly throwing an error when only a single GPU is present.
> Fix NUM_GPUS constant not being set properly when only one GPU is present

- pykokkos/core/fusion/fuse.py
- pykokkos/core/fusion/trace.py
- pykokkos/core/runtime.py
- pykokkos/interface/views.py
Add a new 'naive' fusion strategy which fuses all consecutive `parallel_for` workunits. Reductions and scans are not fused for now. Also replace `PK_TRACE` environment variable with `PK_FUSION`, which can be set to "trace" for only delaying execution (but not actually fusing) or "naive" to delay execution and fuse using the previously mentioned strategy.
> Fusion: add new 'naive' fusion strategy

- docs/.gitignore
- docs/Makefile
- docs/concepts.rst
- docs/conf.py
- docs/docker.rst
- docs/index.rst
- docs/make.bat
- docs/patterns.rst
- docs/policies.rst
- docs/work-units.rst
This PR introduces documentation pages for PyKokkos.
The documentation covers the key concepts: patterns, policies, work units. Also, it covers the docker instructions.
Current limitations: there are still policies that are not described, as well as execution spaces. Will be a separate PR. There will also be a separate PR to make this into GitHub pages.
> doc: Initial documentation for PyKokkos (Sphinx format)

- .github/workflows/array_api.yml
- .github/workflows/main_ci.yml
- .github/workflows/nightly.yml
- pykokkos/core/visitors/visitors_util.py
This PR moves us to a newer version of Python in CI (the latest one we support) and also drops support for 3.8 (as per gh-182).
> versions: Update Python version that we use in CI and drop 3.8 support

- pykokkos/core/runtime.py
- pykokkos/interface/execution_policy.py
This was caused by the recent introduction of execution space instances (which is not applicable to the Debug execution space). This PR fixes the crash by adding checks for Debug as necessary.
> Fix Debug execution space crashing

- Dockerfile
- docs/installation.rst
- requirements.txt
Explicitly defining the range of python versions supported -- this PR has a counterpart in pykokkos-base as well.
> requirements.txt: Updated python version >=3.9, <3.12

- pykokkos/core/fusion/access_modes.py
- pykokkos/core/fusion/trace.py
For now, we will treat views passed to `@pk.function` calls as ReadWrite access. In the future, we need to parse the functions being called as well. This PR also fixes an issue when fusing workunits that are not named.
> Fusion: extract access mode of views passed to functions and fix issue with fusing unnamed workunits

- pre_compile_tools/pre_compile_ufuncs.py
- pykokkos/__init__.py
- pykokkos/lib/ufuncs.py
- tests/test_ufuncs.py
`ufuncs.py`
[+] Adding support for 2D views for the subtract util.
[+] Added support for broadcasting views from scalar uptil 2D and anything inbetween (1D)
`pykokkos/__init__.py`
[+] `broadcast_view(view_or_val, ontoThisView)` is an exposed utility
`test_ufuncs.py`
[+] Added tests for subtract up til 2D -- these trigger broadcast too
[-] Removed annotations in some test kernels to support scalars and views together
> ufuncs: Added subtract support for 2D views

- pykokkos/core/fusion/fuse.py
- pykokkos/core/fusion/future.py
- pykokkos/core/fusion/trace.py
- pykokkos/core/runtime.py
- pykokkos/core/type_inference/args_type_inference.py
- pykokkos/interface/views.py
This PR enables fusion of a single parallel_reduce that with a sequence of parallel_fors that it follows.
> Fusion: allow fusion of a single parallel_reduce with a sequence of parallel_fors 

- pykokkos/core/type_inference/args_type_inference.py
- pykokkos/lib/ufuncs.py
Previously `isinstance` checks for views either used `pk.View` or `pk.ViewType`. The latter is a parent class for views which covers broader sub-classes e.g sub-views, which would not be supported otherwise.
This PR will make this check consistent for `ufuncs` and `args_type_inference` - removing any issues with support for subviews
> Adding consistency for isinstance(<obj>, ViewType)

- pykokkos/interface/views.py
Previously we were using the `data` member, which is a numpy array to hold the pointer to the buffer. This was causing segfaults when accessing Views that wrap cupy arrays.
> Fix accessors for Views that wrap arrays

- mypy.ini
- pykokkos/core/compiler.py
- pykokkos/core/fusion/access_modes.py
- pykokkos/core/fusion/util.py
- pykokkos/core/module_setup.py
- pykokkos/core/optimizations/__init__.py
- pykokkos/core/optimizations/loop_fuse.py
- pykokkos/core/optimizations/memory_ops_fuse.py
- pykokkos/core/optimizations/restrict_views.py
- pykokkos/core/optimizations/util.py
- pykokkos/core/runtime.py
- pykokkos/core/translators/bindings.py
- pykokkos/core/translators/members.py
- pykokkos/core/translators/static.py
- pykokkos/core/visitors/__init__.py
- pykokkos/core/visitors/kokkosfunction_visitor.py
- pykokkos/core/visitors/kokkosmain_visitor.py
- pykokkos/core/visitors/pykokkos_visitor.py
- pykokkos/core/visitors/visitors_util.py
- pykokkos/core/visitors/workunit_visitor.py
This adds a feature (enabled by setting the `PK_RESTRICT` environment variable) to automatically add [`restrict`](https://en.cppreference.com/w/c/language/restrict) to views, which tells the compiler that the restricted views/arrays do not alias, enabling it optimize the code better. The alias analysis is done automatically by PyKokkos.
Ideally we would use the `Kokkos::Restrict` memory trait, however most compilers ignore `restrict` with pointers that are member variables (as it is with Kokkos Views). This PR solves this issue by generating a `KOKKOS_FUNCTION` that accepts the raw view pointers as arguments which we can then use `restrict` with.
> Add optimization that automatically adds the restrict keyword to kernels

- pykokkos/core/optimizations/restrict_views.py
`__restrict__` seems to be supported with GCC, Clang, and NVCC and so is more reliable
> Use __restrict__ instead of Kokkos restrict macro

- pykokkos/core/visitors/pykokkos_visitor.py
- tests/test_AST_translator.py
Fixed by returning an empty statement when a standalone constant expression is encountered. Also added a test.
> Fix issue where using a docstring in a workunit or kokkos function caused a translation error

- tests/test_views.py
In NumPy 2.0, assigning negative values to arrays of unsigned integers raises an `OverflowError`. This PR modifies the test to account for this change in behavior so our tests pass again. In the future we should decide whether we should follow numpy more closely or keep the old behavior.
> Tests: account for numpy 2.0 when testing uint views

- pykokkos/interface/execution_policy.py
TeamPolicy constructor docstring incorrectly copy and pasted from RangePolicy constructor. Update to reflect true description of league size and team size.
> Fix TeamPolicy constructor docstring.

- pykokkos/core/fusion/access_modes.py
- pykokkos/core/fusion/trace.py
Added a safety check to prevent fusion of kernels that could introduce a dependency between threads in the fused kernel. Dependencies can only come from views, so the safety check looks at the what indices are used to access the views. Two kernels which access views only through their thread ID will not introduce a dependency between threads in the fused kernel.
> Add safety check for fusion

- pykokkos/core/fusion/access_modes.py
- pykokkos/core/fusion/trace.py
- pykokkos/core/type_inference/args_type_inference.py
Reduce overhead from PyKokkos when fusing kernels. The two main changes are:
1. No longer restoring an AST's original arguments as that requires a copy
2. Memoizing accesses to the AST
This also relaxes a restriction on fusing two workunits that access views with an index that is a function of the thread ID
> Reduce fusion overhead

- pykokkos/core/visitors/workunit_visitor.py
- pykokkos/interface/__init__.py
- pykokkos/interface/mathematical_special_functions.py
These functions accept and return complex numbers. Since we have not implemented `Kokkos::complex` yet in pykokkos, the current implementation only accepts and returns real numbers.
> Interface: add cyl_bessel_j0 and cyl_bessel_j1 as mathemtical functions

- pykokkos/core/fusion/access_modes.py
- pykokkos/core/fusion/trace.py
This includes a cache issue where multiple calls to the same workunit with different arguments were getting the same view access information. Another issue was that view elements passed to function calls were not being detected properly.
> Tracer: fix caching issue and detect views passed to function calls

- pykokkos/core/fusion/trace.py
Fusing a sequence of parallel fors with parallel reduce leads to less performance in ExaMiniMD. This PR prevents that by fusing the parallel fors alone.
> Tracer: don't fuse parellel reduce or scan workunits with parellel fors due to slowdown

- pykokkos/core/fusion/access_modes.py
This pattern occurs in gups.py, e.g.
```python
data[indices[i]]
```
This fix makes sure we detect that the workunit is reading from indices
> Tracer: fix issue with not detecting view access modes when they are used as a subscript in another view index

- pykokkos/core/optimizations/restrict_views.py
- pykokkos/core/visitors/pykokkos_visitor.py
This removes an extra multiply for indexing 1D and LayoutLeft/LayoutRight 2D views since we know that one of their strides is 1.
> Optimizations: fix indexing of restrict views adding extra operations

- examples/pykokkos/team_thread_mdrange.py
- pykokkos/core/visitors/workunit_visitor.py
- pykokkos/interface/__init__.py
- pykokkos/interface/execution_policy.py
This adds [TeamThreadMDRange](https://kokkos.org/kokkos-core-wiki/API/core/policies/TeamThreadMDRange.html?highlight=teamthreadmdrange#_CPPv4I00E17TeamThreadMDRange) from Kokkos
> Interface: add TeamThreadMDRange
